### ISSUE TITLE
질문 : 필터 라이선스

### ISSUE THREAD

**Issue by Maesil** [gfmaster/adblock-korea-contrib#16]
안녕하세요! 한국어 애드블록 필터를 관리해 주셔서 감사합니다! 근데 이 필터의 라이선스는 무엇인가요?

**Comment by sysilion** [comment]
음.... 꼭 필요가 있을지 모르겠네요.
있다면 그냥 MIT 라이센스 정도가 괜찮을 듯 합니다.

**Comment by Maesil** [comment]
다른 필터 보니까 다 라이선스가 적혀는 있었어요.

https://code.google.com/p/adblock-korea/

이 필터의 대다수를 차지하고 있는 위 필터의 라이선스가 BSD 라이선스이니 그대로 따라가는 것도 좋을 것 같습니다.

**Comment by gfmaster** [comment]
이 리스트를 넘겨받을때 라이선스같은것에 대해 긴 협의가 있지는 않았습니다. 하지만 원 라이선스를 따라 BSD라이선스를 명시하는 것을 검토하겠습니다.
