### ISSUE TITLE
avsnoop.de

### ISSUE THREAD

**Issue by isreport** [gfmaster/adblock-korea-contrib#21]
뻘쭘....

https://avsnoop.de
>avsnoop.de###bottomBanner
>avsnoop.de###adArea
>avsnoop.de###side > .inner > .banner:nth-of-type(3)
>avsnoop.de###side > .inner > .banner:nth-of-type(4)
>avsnoop.de###side > .inner > .banner:nth-of-type(5)
>avsnoop.de###bbslist > .bottom > .banner

덧. ublock 기본 3rd party filter list에 adblock-korea-contrib 선택지가 추가되었네요! ^^

**Comment by Maesil** [comment]
@isreport 
https://github.com/gorhill/uBlock/issues/317

제가 추가해 달라고 요청을 했었어요. ^^

**Comment by isreport** [comment]
@Maesil 
https://github.com/chrisaljoudi/uBlock/issues/1327

아....전 예전에 요청했었는데 uBlock (origin 아닌) 트래커에서는 별 조치가 없어서...잘됐네요!

**Comment by gfmaster** [comment]
어... 음....
korea 라는 취지에는 부합하지 않는것 같습니다만 ^^; 일단 추가했습니다.
