### ISSUE TITLE
개인정보 관련 필터는 어떻게 해야 할까요?

### ISSUE THREAD

**Issue by Maesil** [gfmaster/adblock-korea-contrib#24]
필터 작성을 위해 네트워크 로그를 보던 중 http://dable.io 를 보았습니다. 단순히 개인정보만 수집한다면 당연히 막아야겠지만 좋아할 만한 기사를 제공해 주는 서비스라서 고민이 됩니다. 어떻게 하면 좋을까요?

**Comment by sysilion** [comment]
개인적인 의견으로는
프라이버시 관련 내용은 다른 필터를 이용하는게 낫지 않을까 싶습니다.
아니면 한국용 프라이버시 필터를 만드는것도 나쁘진 않겟네요.

**Comment by gfmaster** [comment]
프라이버시 관련 필터는 따로 관리하는것이 좋을 것 같습니다.


2015-07-14 16:33 GMT+09:00 Bizu <notifications@github.com>:

> 개인적인 의견으로는
> 프라이버시 관련 내용은 다른 필터를 이용하는게 낫지 않을까 싶습니다.
> 아니면 한국용 프라이버시 필터를 만드는것도 나쁘진 않겟네요.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gfmaster/adblock-korea-contrib/issues/24#issuecomment-121153051>
> .
>



-- 
β
