### ISSUE TITLE
Video advertisement  in Naver Webtoon

### ISSUE THREAD

**Issue by rubydragons** [gfmaster/adblock-korea-contrib#27]
For the last few days, new advertisements recently are starting to appear in Naver webtoon website.
They automatically play without any agreement of users as soon as scroll reaches the top of the specific div section where new commercial images and videos are included.

The sources are as follows:
```html
<div id="ppl_image_section" class="ads_sc" style="display:none;">
   <!-- ppl image connected to its link is added this section -->
<div>
<div id="ppl_video_section" class="ads_sc video" style="display:block;">
    <!-- video included this part right over here -->
</div>
```

I'd recommend adding this new filter to remove them:
```html
comic.naver.com##div[id^=ppl]
```

**Comment by gfmaster** [comment]
Reopening issue as a reminder to apply the fix

**Comment by gfmaster** [comment]
updated
