### ISSUE TITLE
디시인사이드 광고차단 관련 팝업 없애는 룰 만들었습니다.

### ISSUE THREAD

**Issue by jaeeonr** [gfmaster/adblock-korea-contrib#37]
gall.dcinside.com##div[style*="position: fixed; left: 50%; top: 380px; margin-left: -219px; z-index: 9999;"]

추가해주세요. 감사합니다.

**Comment by newmsz** [comment]
이걸로 해결되진 않네요 스타일이 다양하게 나타납니다

**Comment by sysilion** [comment]
https://reek.github.io/anti-adblock-killer/
이쪽으로 문의해서 확인해달라는것도 괜찮을거 같네요.

**Comment by jaeeonr** [comment]
죄송해요 제가 했을땐 됬었는데 김유식이 광고차단와 전쟁을 선포해서 다시 막혔네요. 집에가서 업데이트된 스크립트 제작해볼게요.

**Comment by gfmaster** [comment]
룰 업데이트 해주시면 해당 내용으로 반영하겠습니다

**Comment by jaeeonr** [comment]
gall.dcinside.com##body > div:nth-child(6)

gall.dcinside.com##body > div:has(img[alt="광고차단 프로그램을 쓰고 계시나봐요 ㅠㅠ"])

nstatic.dcinside.com/dgn/gallery/images/popup/zze*$image

3번째줄 zze* 주소의 이미지는 광고차단 팝업에만 사용되는것으로 확인했습니다.
또한 3번째룰은 갤러리 안에 들어갔을때만 사용되는것같습니다.

그리고 ublock origin을 감지하고 특수한 처리를 하는 스크립트를 발견했는데 그게 세번째를 작동시키는 특수 경우인지는 잘
모르겠습니다.

감사합니다. :)
