### ISSUE TITLE
 clien.net

### ISSUE THREAD

**Issue by isreport** [gfmaster/adblock-korea-contrib#4]
https://forums.lanik.us/viewtopic.php?f=62&t=22483&sid=dff272b7c2846f862e9356505454dbe1

fanboy gave me this github repo link as a reply

**Comment by gfmaster** [comment]
I will add the entry tonight.
Thanks for contribution

**Comment by isreport** [comment]
doesn't seem like entry has been added or effective (windows firefox 37, ublock origin 0.9.5.0 with adblock-korea-contrib filter added as custom)
![screenshot](http://i.imgur.com/19kf1Ul.png)

**Comment by sysilion** [comment]
using my fork https://github.com/sysilion/adblock-korea-contrib
or just wait a little.
already ive to pull request . :)

**Comment by gfmaster** [comment]
merged sysilion's pull request which contains this update
thank you sysilion
