### ISSUE TITLE
/omniture/ preventing content from loading

### ISSUE THREAD

**Issue by Palf994** [gfmaster/adblock-korea-contrib#42]
The /omniture/ filter causes article content to not load on thehawkeye.com
(eg. [http://www.thehawkeye.com/news/20170925/defense-attorney-seeks-grand-jury-testimony](http://www.thehawkeye.com/news/20170925/defense-attorney-seeks-grand-jury-testimony))

**Comment by gfmaster** [comment]
fixed with commit f10e026
