### ISSUE TITLE
about /overture/ filter

### ISSUE THREAD

**Issue by yvelkram** [gfmaster/adblock-korea-contrib#45]
I even not guess why there is a overture keyword filter. It's just a kind of music from, especially used to before opera.

> an orchestral piece at the beginning of an opera, suite, play, oratorio, or other extended composition.
google said.

**Comment by gfmaster** [comment]
Overture was name of ad company, a subsidiary of Yahoo. It withdrew from South Korean market in 2012 and the filter in question must be legacy of that era.
