### ISSUE TITLE
hayan.tv

### ISSUE THREAD

**Issue by isreport** [gfmaster/adblock-korea-contrib#6]
has adblock detection which can be disabled through adding whitelist entry 
> @@||hayan.tv/adsbygoogle.js?*

처음에 영어로 쓰기 시작해서 이제와서 뻘쭘하긴 한데...그냥 한글로 쓰는게 좋을까요?

**Comment by sysilion** [comment]
전 한국인이 맞습니다만, gfmaster님이 한글을 잘 쓰시는지는 잘 모르겟네요.
일단 제 fork에는 추가해두겠습니다. :)
감사합니다.

**Comment by gfmaster** [comment]
한국어 이용에 문제 없는 한국인입니다. 편하게 커멘트 남겨주세요 ^^
최근 데스크탑 브라우저로 서핑을 자주 하지 않다보니 업데이트가 늦는 경향이 있지만 여러분들의 관심에 감사드립니다. sysilion님의 pull request는 merge 했으니 곧 확인하실 수 있을겁니다.
좀 더 자주 커밋하도록 할께요 ^^:;
