### ISSUE TITLE
torrentdn.com

### ISSUE THREAD

**Issue by isreport** [gfmaster/adblock-korea-contrib#8]
필터가 원하는 만큼 깔끔하게 떨어지지는 않지만 일단 올려봅니다
>torrentdn.com##A[href="/to_toy.html"]
>torrentdn.com##A[href="/to_toptoon.html"]
>torrentdn.com##DIV[style="float:left;width:130px;border:1;margin:5px;word-break: break-all;"]

**Comment by gfmaster** [comment]
업데이트 했습니다
